### ISSUE TITLE
popupwindow内容区域会变透明

### ISSUE THREAD

**Issue by Bobyang912** [BakerJQ/Android-BackgroundDarkPopupWindow#3]
BackgroundDarkPopupWindow不知道在什么情况下，内容区域会变透明，灰色的透明状，退出重新进来一下又好了，下次不知道什么时候又会出现

**Comment by BakerJQ** [comment]
抱歉，这个已经不维护了，这个开发针对的版本太老了，现在已经没必要使用这个去实现类似的效果了
